---
- hosts: AD
  become: true
  gather_facts: no
  vars:
   newpass: n1dpsI$`W>4i]yOT
  
  tasks:
  - name: Change HostName
    command: hostnamectl set-hostname {{ hostname }}
  
  - name: AD server entry
    lineinfile:
      path: /etc/resolv.conf
      line: 'search automation.local'
      insertbefore: 'nameserver 8.8.8.8'
  
  - name: AD server entry2
    lineinfile:
       path: /etc/resolv.conf
       line: 'nameserver 10.10.120.38'
       insertafter: 'search automation.local'
  
  - name: Remove AD ROOT ACCESS
    shell: cd /etc/sudoers.d/;rm -f INTATM-*-ROOT-ACCESS
   
  - name: Joinining the AD realm
    shell: echo '{{ newpass }}' | realm join --user srv.linux automation.local -v
  
  - name: SSD file entry 
    command:  sed -i "${services = nss, pam} i \ \ ${default_domain_suffix = automation.local}" /etc/sssd/sssd.conf 
  - name: ssh
    shell: realm permit -g C4C-INTATM-`hostname`-SSH-ACCESS
  
  - name: add AD group access permit
    shell: echo  "%C4C-INTATM-`hostname|tr “[a-z]” “[A-Z]”`-ROOT-ACCESS        ALL=(ALL)       ALL" > /etc/sudoers.d/C4C-INTATM-`hostname|tr “[a-z]” “[A-Z]”`-ROOT-ACCESS
  
