---
- hosts: post
  become: true
  gather_facts: no
  
  tasks:
  - name: chaging entries in chrony
    lineinfile: 
      path: /etc/chrony.conf
      regexp: 'pool 2.rhel.pool.ntp.org iburst'
      line: 'server 10.174.30.107 iburst'
      backrefs: yes

