---
- name: Change root password for all servers
  hosts: MY
  vars:
    password_length: 16  # Define the desired length of the random password
  tasks:
    - name: Generate random password
      community.general.random_password:
        length: "{{ password_length }}"
        special: yes
      register: random_password

    - name: Set root password
      user:
        name: root
        password: "{{ random_password.password }}"
        update_password: always

    - name: Display root password
      debug:
        msg: "Root password for {{ inventory_hostname }}: {{ random_password.password }}"
