---
- hosts: MF
  become: true
  gather_facts: no
  vars:
   newpass: Q!w@e3r4@1$3$#$
  
  tasks:
  - name: Update Root user's Password
    user:
     name: root
     update_password: always
     password: "{{ newpass | password_hash('sha512') }}"
