---
- name: Reset root password with random passwords
  hosts: MY
  become: true
  gather_facts: false
  vars:
    password_file: "/root/passwords.txt"
  tasks:
    - name: Generate random password
      shell: "pwgen -s 12 1"
      register: random_password
      ignore_errors: yes
 
    - name: Set root password to random password
      user:
        name: root
        password: "{{ random_password.stdout }}"
        update_password: always
      ignore_errors: yes
 
    - name: Save password to file
      lineinfile:
        path: "{{ password_file }}"
        line: "Host: {{ inventory_hostname }} Password: {{ random_password.stdout }}"
        create: yes
