---
- hosts: MF
  gather_facts: false
  become: true
  vars:
  tasks:
  - name: Enabling ssh-key only root access
    lineinfile:
        dest: /etc/ssh/sshd_config
        backup: yes
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'


  - name: Restart sshd
    systemd:
        state: restarted
        daemon_reload: yes
        name: sshd

