---
- hosts: SCD
  become: true
  gather_facts: no
  
  tasks:
  - name: Update Root user's Password
    shell: 'echo "----------------1.1.1.4 Ensure mounting of udf filesystems is disabled - modprobe--------------" > /tmp/sdc.txt'
    shell: 'modprobe -n -v udf >> /tmp/sdc.txt'
    shell: 'lsmod | grep udf  >> /tmp/sdc.txt'
    shell: 'echo "---------------- 1.1.2 Ensure /tmp is configured - config check-----------------------" >> /tmp/sdc.txt'
    shell: 'cat /etc/fstab |grep -i /tmp >> /tmp/sdc.txt'
    shell: 'echo "---------------- 1.1.23 Disable USB Storage - modprobe-----------------------" >> /tmp/sdc.txt'
    shell: 'cat /etc/modprobe.d/usb_storage.conf >> /tmp/sdc.txt'
    shell: 'lsmod | grep usb-storage >> /tmp/sdc.txt'
    shell: 'echo "---------------- 1.1.17 Ensure noexec option set on /dev/shm partition-----------------------" >> /tmp/sdc.txt'
    shell: 'mount | grep -E '\s/dev/shm\s' | grep -v noexec >> /tmp/sdc.txt'
    shell: 'mount |grep -i /dev/shm >> /tmp/sdc.txt'
    shell: 'echo "---------------- 1.3.2 Ensure sudo commands use pty-----------------------" >> /tmp/sdc.txt'
    shell: 'cat  /etc/sudoers |grep -i use_pty >> /tmp/sdc.txt'
    shell: 'grep -Ei '^\s*Defaults\s+(\[^#]+,\s*)?use_pty' /etc/sudoers >> /tmp/sdc.txt'
    shell: 'echo "---------------- 1.3.3 Ensure sudo log file exists-----------------------" >> /tmp/sdc.txt'
    shell: 'cat /etc/sudoers |grep -i log >> /tmp/sdc.txt'
    shell: 'echo "---------------- 1.5.1 Ensure permissions on bootloader config are configured------------------" >> /tmp/sdc.txt'
    shell: 'ls -lrt /boot/grub2/grub.cfg >> /tmp/sdc.txt'
    shell: 'ls -lrt /boot/grub2/user.cfg >> /tmp/sdc.txt'
    shell: 'echo "---------------- 1.8.1.2 Ensure local login warning banner is configured properly - banner text : [FAILED]-----" >> /tmp/sdc.txt'
    shell: 'cat /etc/issue >> /tmp/sdc.txt'
    shell: 'grep -E -i "(\\\v|\\\r|\\\m|\\\s|$(grep '^ID=' /etc/os-release | cut -d= -f2 | sed -e 's/"//g'))" /etc/issue >> /tmp/sdc.txt'
    shell: 'echo "---------------- 1.8.1.3 Ensure remote login warning banner is configured properly - banner text" : [FAILED]----------" >> /tmp/sdc.txt'
    shell: 'cat /etc/issue >> /tmp/sdc.txt'
    shell: 'grep -E -i "(\\\v|\\\r|\\\m|\\\s|$(grep '^ID=' /etc/os-release | cut -d= -f2 | sed -e 's/"//g'))" /etc/issue >> /tmp/sdc.txt'
    shell: 'echo "---------------- 1.9 Ensure updates, patches, and additional security software are installed" : [FAILED] ----" >> /tmp/sdc.txt'
    shell: 'echo "---------------- 2.2.1.2 Ensure chrony is configured - NTP server" : [FAILED] -----------------------" >> /tmp/sdc.txt'
    shell: 'cat /etc/chrony.conf |grep -i server >> /tmp/sdc.txt'
    shell: 'ps -ef | grep chronyd >> /tmp/sdc.txt'
    shell: 'echo "---------------- 2.3.2 Ensure telnet client is not installed" : [FAILED] -----------------------" >> /tmp/sdc.txt'
    shell: 'rpm -q telnet >> /tmp/sdc.txt'
    shell: 'echo "---------------- 3.1.1 Ensure IP forwarding is disabled - ipv6 sysctl" : [FAILED] -----------------------" >> /tmp/sdc.txt'
    shell: 'sysctl net.ipv4.ip_forward >> /tmp/sdc.txt'
    shell: 'grep -E -s "^\s*net\.ipv4\.ip_forward\s*=\s*1" /etc/sysctl.conf >> /tmp/sdc.txt'
    shell: 'grep -E -s "^\s*net\.ipv4\.ip_forward\s*=\s*1" /etc/sysctl.d/*.conf >> /tmp/sdc.txt'
    shell: 'grep -E -s "^\s*net\.ipv4\.ip_forward\s*=\s*1" /usr/lib/sysctl.d/*.conf >> /tmp/sdc.txt'
    shell: 'grep -E -s "^\s*net\.ipv4\.ip_forward\s*=\s*1" /run/sysctl.d/*.conf >> /tmp/sdc.txt'
    shell: 'sysctl net.ipv6.conf.all.forwarding >> /tmp/sdc.txt'
    shell: 'echo "---------------- 3.2.1 Ensure source routed packets are not accepted - 'net.ipv6.conf.all.accept_source_route=0 >> /tmp/sdc.txt'
    shell: 'sysctl net.ipv4.conf.all.accept_source_route >> /tmp/sdc.txt'
    shell: 'sysctl net.ipv4.conf.default.accept_source_route >> /tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.all\.accept_source_route" /etc/sysctl.conf >> /tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.all\.accept_source_route" /etc/sysctl.d/*.conf >> /tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.all\.accept_source_route" /usr/lib/sysctl.d/*.conf >> /tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.all\.accept_source_route" /run/sysctl.d/*.conf >> /tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.all\.defa^Cource_route" /run/sysctl.d/*.conf >> /tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.default\.accept_source_route" /run/sysctl.d/*.conf >> /tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.default\.accept_source_route" /usr/lib/sysctl.d/*.conf >> /tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.default\.accept_source_route" /etc/sysctl.d/*.conf >> /tmp/sdc.txt'
    shell: 'sysctl net.ipv6.conf.all.accept_source_route >> /tmp/sdc.txt'
    shell: 'sysctl net.ipv6.conf.default.accept_source_route >> /tmp/sdc.txt'
    shell: 'echo "---------------- 3.2.2 Ensure ICMP redirects are not accepted - sysctl 'net.ipv6.conf.all.accept_redirects'--------" >> /tmp/sdc.txt'
    shell: 'echo "---------------- 3.2.2 Ensure ICMP redirects are not accepted - sysctl 'net.ipv6.conf.default.accept_redirec >> /tmp/sdc.txt'
    shell: 'sysctl net.ipv4.conf.all.accept_redirects >>/tmp/sdc.txt'
    shell: 'sysctl net.ipv4.conf.default.accept_redirects >>/tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.all\.accept_redirects" /etc/sysctl.conf >>/tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.all\.accept_redirects" /etc/sysctl.d/*.conf >>/tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.all\.accept_redirects" /usr/lib/sysctl.d/*.conf >>/tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.all\.accept_redirects" /run/sysctl.d/*.conf >>/tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.default\.accept_redirects" /etc/sysctl.conf >>/tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.default\.accept_redirects" /etc/sysctl.d/*.conf >>/tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.default\.accept_redirects" /usr/lib/sysctl.d/*.conf >>/tmp/sdc.txt'
    shell: 'grep "net\.ipv4\.conf\.default\.accept_redirects" /run/sysctl.d/*.conf >>/tmp/sdc.txt'
    shell: 'sysctl net.ipv6.conf.all.accept_redirects >>/tmp/sdc.txt'
    shell: 'sysctl net.ipv6.conf.default.accept_redirects >>/tmp/sdc.txt'
    shell: 'echo "---------------- 3.2.9 Ensure IPv6 router advertisements are not accepted - 'grep net.ipv6.conf.default.acce--------------" >>/tmp/sdc.txt'
    shell: 'echo "---------------- 3.2.9 Ensure IPv6 router advertisements are not accepted - 'sysctl net.ipv6.conf.default.ac----------" >>/tmp/sdc.txt'
    shell: 'sysctl net.ipv6.conf.all.accept_ra >>/tmp/sdc.txt'
    shell: 'sysctl net.ipv6.conf.default.accept_ra >>/tmp/sdc.txt'
    shell: 'echo "---------------- 4.2.1.5 Ensure rsyslog is configured to send logs to a remote log host" : [FAILED] --------" >>/tmp/sdc.txt'
    shell: 'cat /etc/rsyslog.conf |grep -i 514 >>/tmp/sdc.txt'
    shell: 'systemctl is-enabled rsyslog >>/tmp/sdc.txt'
    shell: 'echo "---------------- 4.2.3 Ensure permissions on all logfiles are configured" : [FAILED] -----------------------" >>/tmp/sdc.txt'
    shell: 'find /var/log/ -type f -perm /g+wx,o+rwx -exec chmod g-wx,o-rwx '{}' + >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.2 Ensure SSH access is limited - sshd output" : [FAILED] -----------------------" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i allowusers >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i allowgroups >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i denyusers >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i denygroups >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep -Pi  >>/tmp/sdc.txt'
    shell: 'grep -Pi '^\h*(allow|deny)(users|groups)\h+\H+(\h+.*)?$' /etc/ssh/sshd_config >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.5 Ensure SSH LogLevel is appropriate - sshd output" : [FAILED] -----------------------" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i LogLevel >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep logl >>/tmp/sdc.txt'
    shell: 'grep -i 'loglevel' /etc/ssh/sshd_config | grep -Evi 'INFO' >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.7 Ensure SSH MaxAuthTries is set to 4 or less - sshd output" : [FAILED] ---------------" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i MaxAuthTries >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep maxa >>/tmp/sdc.txt'
    shell: 'grep -Ei '^\s*maxauthtries\s+([5-9]|[1-9][0-9]+)' /etc/ssh/sshd_config >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.8 Ensure SSH IgnoreRhosts is enabled - sshd output" : [FAILD] -----------------------" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i IgnoreRhosts >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep igno >>/tmp/sdc.txt'
    shell: 'grep -Ei '^\s*ignorerhosts\s+no\b' /etc/ssh/sshd_config >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.9 Ensure SSH HostbasedAuthentication is disabled - sshd output" : [FAILED] ------------" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i HostbasedAuthentication >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep host >>/tmp/sdc.txt'
    shell: 'grep -Ei '^\s*HostbasedAuthentication\s+yes' /etc/ssh/sshd_config >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.11 Ensure SSH PermitEmptyPasswords is disabled - sshd output" : [FAILED] --------------" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i PermitEmptyPasswords >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep perm >>/tmp/sdc.txt'
    shell: 'grep -Ei '^\s*PermitEmptyPasswords\s+yes' /etc/ssh/sshd_config >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.12 Ensure SSH PermitUserEnvironment is disabled - sshd output" : [FAILED] -------------" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i PermitUserEnvironment >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep perm >>/tmp/sdc.txt'
    shell: 'grep -Ei '^\s*PermitUserEnvironment\s+yes' /etc/ssh/sshd_config >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.13 Ensure SSH Idle Timeout Interval is configured - ClientAliveInterval sshd output" :--"  >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i ClientAliveInterval >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i ClientAliveCountMax >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep client  >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep client >>/tmp/sdc.txt'
    shell: 'grep -Ei '^\s*ClientAliveInterval\s+(0|9[0-9][1-9]|[1-9][0-9][0-9][0-9]+|1[6-9]m|[2-9][0-9]m|[1-9][0-9][0-9]+m)\b' >>/tmp/sdc.txt'
    shell: 'grep -Ei '^\s*ClientAliveCountMax\s+([1-9]|[1-9][0-9]+)\b' /etc/ssh/sshd_config >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.14 Ensure SSH LoginGraceTime is set to one minute or less - sshd output" : [FAILED] ---" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i LoginGraceTime >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep logi >>/tmp/sdc.txt'
    shell: 'grep -Ei '^\s*LoginGraceTime\s+(0|6[1-9]|[7-9][0-9]|[1-9][0-9][0-9]+|[^1]m)' /etc/ssh/sshd_config >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.15 Ensure SSH warning banner is configured" : [FAILED] -------------vm----------" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i Banner >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep bann >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.16 Ensure SSH PAM is enabled - sshd output" : [FAILED] -----------------------" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i UsePAM >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep -i usepam >>/tmp/sdc.txt'
    shell: 'grep -Ei '^\s*UsePAM\s+no' /etc/ssh/sshd_config >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.18 Ensure SSH MaxStartups is configured - sshd output" : [FAILED] ---------------------" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i MaxStartups >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep -i maxstartups >>/tmp/sdc.txt'
    shell: 'grep -Ei '^\s*maxstartups\s+(((1[1-9]|[1-9][0-9][0-9]+):([0-9]+):([0-9]+))|(([0-9]+):(3[1-9]|[4-9][0-9]|[1-9][0-9] >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.2.19 Ensure SSH MaxSessions is set to 4 or less - sshd output" : [FAILED] ---------------" >>/tmp/sdc.txt'
    shell: 'cat /etc/ssh/sshd_config |grep -i MaxSessions >>/tmp/sdc.txt'
    shell: 'sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep -i maxsessions >>/tmp/sdc.txt'
    shell: 'grep -Ei '^\s*MaxSessions\s+(1[1-9]|[2-9][0-9]|[1-9][0-9][0-9]+)' /etc/ssh/sshd_config >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.4.4 Ensure password hashing algorithm is SHA-512 - password-auth" : [FAILED] ------------" >>/tmp/sdc.txt'
    shell: 'grep -E '^\s*password\s+sufficient\s+pam_unix.so\s+.*sha512\s*.*$' /etc/pam.d/password-auth >>/tmp/sdc.txt'
    shell: 'grep -E '^\s*password\s+sufficient\s+pam_unix.so\s+.*sha512\s*.*$' /etc/pam.d/system-auth >>/tmp/sdc.txt'
    shell: 'echo "---------------- 5.7 Ensure access to the su command is restricted - wheel group contains root" : [FAILED] ----" >>/tmp/sdc.txt'
    shell: 'grep pam_wheel.so /etc/pam.d/su >>/tmp/sdc.txt'
    shell: 'grep wheel /etc/group >>/tmp/sdc.txt'
