---
- hosts: AMAN
  become: true
  gather_facts: no

  tasks:
    - name: taking sshd backup
      command: cp /etc/ssh/sshd_config /etc/ssh/sshd_config-20230724
    
    - name: chaging kex-alg in ssh
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^KexAlgorithms diffie-hellman-group1-sha1'
        line: "KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256"
        
    - name: chaging macs in ssh    
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MACs hmac-sha1'
        line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
         
    - name: chaging ciphers in sshd
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: '^Ciphers'
        line: "Ciphers aes256-ctr,aes192-ctr,aes128-ctr"
  
        
