---
- name: Reset root password with unique random passwords
  hosts: MY
  gather_facts: no
  become: true
  vars:
    password_length: 12
    password_complexity: "A-Za-z0-9!@#$%^&*()_+[]{}|;:,.<>?"
    passwords_file: "/tmp/root_passwords.txt"  # Specify the path to the passwords file on your Ansible control node

  tasks:
    - name: Construct lookup string
      ansible.builtin.set_fact:
        lookup_string: "/dev/null chars={{ password_complexity }} length={{ password_length }}"

    - name: Generate random password
      ansible.builtin.set_fact:
        root_password: "{{ lookup('password', lookup_string) }}"

    - name: Change root password
      ansible.builtin.user:
        name: root
        password: "{{ root_password | password_hash('sha512') }}"
        update_password: always

    - name: Display generated password
      debug:
        msg: "The root password for {{ inventory_hostname }} is {{ root_password }}"

    - name: Save root password to file
      ansible.builtin.lineinfile:
        path: "{{ passwords_file }}"
        line: "Server: {{ inventory_hostname }} | Root Password: {{ root_password }}"
        create: yes
